# Goal
std_msgs/Header header

uint16 search_object
uint16 NO_OBJECT=0
uint16 BOTTLE=1
uint16 OG_HAMMER=2
uint16 ORANGE_HAMMER=3
uint16 ARUCO=4

uint16 search_pattern
uint16 NO_PATTERN=0
uint16 SPIRAL=1
uint16 LAWNMOWER=2

# Lane Spacing
float32 search_param_1  
# Radius for Spiral / Step Size for Lawnmower
float32 search_param_2 

GPSWaypoint[] nav_waypoints 

---
# Result
std_msgs/Header header

uint16 ack
uint16 CANCELED=0
uint16 SUCCESS=1
uint16 FAILED=2

---
# Feedback
std_msgs/Header header

uint16 mission_state
uint16 IDLE=0
uint16 MOVING_TO_START=1
uint16 SEARCHING=2
uint16 WAITING_FOR_NAV_IDLE=3
uint16 INVESTIGATING=4
uint16 RETURNING_TO_SEARCH=5
uint16 SUCCESS=6
uint16 FAILED=7
uint16 RETURNING_HOME=8
uint16 STOPPED=9
